/* Portfolio général (racine). Pas de code d’accès, pas d’entreprise. */
window.SITE = {
  "posteCards": 4,
  "texts": {
    "fr": {
      "site_title": "Timo Marguerat-Trichard — Portfolio",
      "landing_kicker": "Portfolio · Alternance business development",
      "landing_title": "Bonjour.<span>Je suis Timo.</span>",
      "landing_intro": "Un parcours international, une vraie culture du terrain et l’envie de faire avancer les projets commerciaux.",
      "landing_pitch": "Étudiant en Master Programme Grande École à Montpellier Business School, je cherche une alternance de deux ans en business development : prospection B2B, SDR, BDR ou chargé d’affaires.",
      "about_p2": "Aujourd’hui en Master Programme Grande École à Montpellier Business School, je veux prolonger ce fil dans une alternance en développement commercial : comprendre les enjeux d’un client, créer la relation et faire avancer les projets.",
      "nav_poste": "Ce que j’apporte",
      "page_poste": "Ce que j’apporte",
      "poste_kicker": "Ce que j’apporte",
      "poste_title": "Ce que je peux <em>apporter.</em>",
      "poste_lead": "Quatre choses que j’ai déjà pratiquées sur le terrain et que j’amène dans une équipe commerciale.",
      "poste_c1_label": "01 / Prospecter",
      "poste_c1_title": "Ouvrir la conversation",
      "poste_c1_p": "Prospection et relances chez DSA Automobile, devis B2B chez Atelier du Ride : je sais présenter une offre en quelques phrases et adapter mon discours à mon interlocuteur.",
      "poste_c2_label": "02 / Organiser",
      "poste_c2_title": "Tenir plusieurs dossiers",
      "poste_c2_p": "Jusqu’à 40 mandats en parallèle, des événements à forte affluence, des commandes et un suivi client : je garde toujours la prochaine étape en vue.",
      "poste_c3_label": "03 / Comprendre",
      "poste_c3_title": "Tech & IA au quotidien",
      "poste_c3_p": "ChatGPT Pro depuis 2022, Claude depuis 2025, WordPress, Shopify, GitHub : j’aime comprendre un produit en profondeur avant d’en parler. Ce site en est un exemple.",
      "poste_c4_label": "04 / Chiffrer",
      "poste_c4_title": "Marges & reporting",
      "poste_c4_p": "Devis, rentabilité des commandes, suivi budgétaire et reporting sous Excel : je mesure ce que je fais pour l’améliorer.",
      "co_letter_title": "Parlons de <em>votre prochaine alternance.</em>",
      "co_letter_p": "Je cherche une alternance de deux ans à partir d’octobre 2026. Écrivez-moi ou téléchargez mon CV.",
      "footer_location_value": "Montpellier"
    },
    "en": {
      "site_title": "Timo Marguerat-Trichard — Portfolio",
      "landing_kicker": "Portfolio · Business development work-study",
      "landing_title": "Hello.<span>I’m Timo.</span>",
      "landing_intro": "An international background, hands-on experience and the drive to move sales projects forward.",
      "landing_pitch": "A Master’s student at Montpellier Business School, I am looking for a two-year work-study role in business development: B2B prospecting, SDR, BDR or account executive.",
      "about_p2": "Now in a Master in Management at Montpellier Business School, I want to carry this into a business development work-study role: understanding a client’s challenges, building the relationship and moving projects forward.",
      "nav_poste": "What I bring",
      "page_poste": "What I bring",
      "poste_kicker": "What I bring",
      "poste_title": "What I can <em>bring.</em>",
      "poste_lead": "Four things I have already practised in the field and bring to a sales team.",
      "poste_c1_label": "01 / Prospect",
      "poste_c1_title": "Opening the conversation",
      "poste_c1_p": "Prospecting and follow-up at DSA Automobile, B2B quotes at Atelier du Ride: I can pitch an offer in a few sentences and adapt it to the person I am talking to.",
      "poste_c2_label": "02 / Organise",
      "poste_c2_title": "Handling many files",
      "poste_c2_p": "Up to 40 mandates in parallel, high-volume events, orders and client follow-up: I always keep the next step in sight.",
      "poste_c3_label": "03 / Understand",
      "poste_c3_title": "Tech & AI every day",
      "poste_c3_p": "ChatGPT Pro since 2022, Claude since 2025, WordPress, Shopify, GitHub: I like to understand a product in depth before talking about it. This site is one example.",
      "poste_c4_label": "04 / Count",
      "poste_c4_title": "Margins & reporting",
      "poste_c4_p": "Quotes, order profitability, budget monitoring and Excel reporting: I measure what I do so I can improve it.",
      "co_letter_title": "Let’s talk about <em>your next work-study hire.</em>",
      "co_letter_p": "I am looking for a two-year work-study position starting October 2026. Write to me or download my CV.",
      "footer_location_value": "Montpellier"
    }
  }
};
