/* Site de candidature HOKTA. Modifier ici les textes propres à cette entreprise. */
window.SITE = {
  "company": "HOKTA",
  "accessCode": "drone",
  "posteCards": 5,
  "companyCards": 3,
  "mailSubject": "Candidature alternance prospection B2B — Timo",
  "texts": {
    "fr": {
      "nav_company": "HOKTA",
      "footer_location_value": "Montpellier / Béziers",
      "landing_kicker": "Candidature · Alternance prospection B2B",
      "landing_title": "Bonjour HOKTA.<span>Je suis peut-être votre homme.</span>",
      "landing_intro": "Du terrain, de la relance et une vraie curiosité pour la tech : de quoi ouvrir des portes à vos drones.",
      "access_note": "Indice : ce qui survole vos sites, en un mot.",
      "about_p2": "Aujourd’hui en Master Programme Grande École à Montpellier Business School, je veux prolonger ce fil dans une alternance en développement commercial B2B : identifier les bons interlocuteurs, comprendre leurs enjeux et transformer un premier appel en rendez-vous.",
      "landing_pitch": "Étudiant en Master Programme Grande École à Montpellier Business School, je cherche une alternance de deux ans en prospection et développement commercial B2B, à Béziers, dès octobre 2026.",
      "poste_kicker": "Pour le poste",
      "poste_title": "Vos missions, <em>mes preuves.</em>",
      "poste_lead": "Votre annonce décrit cinq missions. Pour chacune, voici ce que j’ai déjà fait sur le terrain.",
      "poste_c1_label": "01 / Prospecter",
      "poste_c1_title": "Décrocher et accrocher",
      "poste_c1_p": "Chez DSA Automobile, j’ai prospecté vendeurs et acheteurs au quotidien. Je sais présenter une offre en quelques phrases et adapter mon discours à un particulier comme à un professionnel.",
      "poste_c2_label": "02 / Qualifier",
      "poste_c2_title": "Trouver qui décide",
      "poste_c2_p": "Devis B2B chez Atelier du Ride, fournisseurs et partenaires chez Arlett : j’ai appris à comprendre vite l’activité d’une structure et à identifier la personne qui tranche.",
      "poste_c3_label": "03 / Obtenir le rendez-vous",
      "poste_c3_title": "Relancer jusqu’à la réponse",
      "poste_c3_p": "Relances clients, vendeurs et fournisseurs, négociation jusqu’à la conclusion : je fais avancer un échange étape par étape, sans le laisser retomber.",
      "poste_c4_label": "04 / Piloter",
      "poste_c4_title": "Un pipeline à jour",
      "poste_c4_p": "Suivi de 40 mandats en parallèle, reporting sous Excel, outils de caisse et de facturation : je tiens mes chiffres et je mesure ce qui fonctionne.",
      "co_kicker": "Pourquoi HOKTA",
      "co_title": "Ce qui m’attire chez <em>HOKTA.</em>",
      "co_lead": "Une technologie concrète, des clients très différents et un poste où l’on voit tout de suite le résultat de ses efforts.",
      "co_card1_title": "Une tech qui se montre.",
      "co_card1_p": "Des drones et des stations automatisées qui surveillent de vrais sites : un produit concret, qu’on a envie de présenter au téléphone puis en démonstration.",
      "co_card2_title": "Des interlocuteurs variés.",
      "co_card2_p": "Industriels, collectivités, gestionnaires d’espaces naturels : apprendre à parler à un directeur d’exploitation comme à un élu, c’est exactement ce que je veux travailler.",
      "co_card3_title": "Une vraie progression.",
      "co_card3_p": "Commencer par la prospection, participer aux rendez-vous, puis monter en compétence sur la vente de solutions complexes : c’est la trajectoire que je recherche.",
      "co_letter_title": "Landry, je serais ravi de vous montrer <em>comment je prospecte.</em>",
      "co_letter_p": "Je vous propose de l’énergie, de la méthode et l’envie d’ouvrir des portes pour HOKTA, depuis Béziers.",
      "poste_c5_label": "05 / Vendre la tech",
      "poste_c5_title": "Comprendre avant de vendre",
      "poste_c5_p": "Réparation de matériel technique, outils numériques, IA au quotidien : j’aime comprendre un produit en profondeur avant d’en parler. Une station automatisée, ça s’apprend.",
      "exp1_role": "Prospection · qualification · négociation",
      "exp1_desc": "J’ai assuré le suivi des mandats, de la prospection à la coordination entre vendeurs et acheteurs : appels, qualification des demandes, relances et négociation jusqu’à la vente. J’ai appris à gérer plusieurs dossiers en parallèle sans perdre la prochaine étape.",
      "exp1_li1": "Jusqu’à 40 mandats en gestion",
      "exp1_li2": "Prospection, qualification et relances",
      "exp1_li3": "Négociation jusqu’à la vente",
      "site_title": "Bonjour HOKTA — Timo"
    },
    "en": {
      "nav_company": "Why HOKTA",
      "footer_location_value": "Montpellier / Béziers",
      "landing_kicker": "Application · B2B prospecting work-study",
      "landing_title": "Hello, HOKTA.<span>I might be the person you’re looking for.</span>",
      "landing_intro": "Field experience, persistent follow-up and a real curiosity for tech: what it takes to open doors for your drones.",
      "access_note": "Hint: what flies over your sites, in one word (in French).",
      "about_p2": "Now in a Master in Management at Montpellier Business School, I want to carry this into a B2B business development work-study role: finding the right contacts, understanding their challenges and turning a first call into a meeting.",
      "landing_pitch": "A Master’s student at Montpellier Business School, I am looking for a two-year work-study role in B2B prospecting and business development, in Béziers, from October 2026.",
      "poste_kicker": "For the role",
      "poste_title": "Your tasks, <em>my evidence.</em>",
      "poste_lead": "Your job post lists five tasks. For each one, here is what I have already done in the field.",
      "poste_c1_label": "01 / Prospect",
      "poste_c1_title": "Getting through, getting interest",
      "poste_c1_p": "At DSA Automobile I prospected sellers and buyers every day. I can pitch an offer in a few sentences and adapt it to an individual or a business.",
      "poste_c2_label": "02 / Qualify",
      "poste_c2_title": "Finding the decision-maker",
      "poste_c2_p": "B2B quotes at Atelier du Ride, suppliers and partners at Arlett: I learned to grasp how an organisation works quickly and who makes the call.",
      "poste_c3_label": "03 / Book the meeting",
      "poste_c3_title": "Following up until I get an answer",
      "poste_c3_p": "Chasing clients, sellers and suppliers, negotiating through to closing: I move a conversation forward step by step and keep it alive.",
      "poste_c4_label": "04 / Manage",
      "poste_c4_title": "An up-to-date pipeline",
      "poste_c4_p": "Up to 40 mandates in parallel, Excel reporting, POS and invoicing tools: I keep track of my numbers and measure what works.",
      "co_kicker": "Why HOKTA",
      "co_title": "What draws me to <em>HOKTA.</em>",
      "co_lead": "Tangible technology, very different clients and a role where you see the result of your efforts straight away.",
      "co_card1_title": "Tech you can show.",
      "co_card1_p": "Drones and automated stations monitoring real sites: a concrete product you want to present on the phone, then in a demo.",
      "co_card2_title": "A wide range of contacts.",
      "co_card2_p": "Industrial firms, local authorities, nature-area managers: learning to talk to an operations director as well as an elected official is exactly what I want to work on.",
      "co_card3_title": "Real progression.",
      "co_card3_p": "Start with prospecting, join the meetings, then build up to selling complex solutions: that is the path I am looking for.",
      "co_letter_title": "Landry, I would love to show you <em>how I prospect.</em>",
      "co_letter_p": "I can bring energy, method and the drive to open doors for HOKTA, from Béziers.",
      "poste_c5_label": "05 / Sell tech",
      "poste_c5_title": "Understand before you sell",
      "poste_c5_p": "Repairing technical gear, digital tools, AI every day: I like to understand a product in depth before talking about it. An automated station can be learned.",
      "exp1_role": "Prospecting · qualification · negotiation",
      "exp1_desc": "I managed mandates from prospecting through to coordinating sellers and buyers: calls, qualifying requests, follow-ups and negotiation through to the sale. It taught me to run several files at once without losing the next step.",
      "exp1_li1": "Up to 40 mandates at once",
      "exp1_li2": "Prospecting, qualification and follow-up",
      "exp1_li3": "Negotiation through to the sale",
      "site_title": "Hello HOKTA — Timo"
    }
  }
};
