/* Site de candidature Loopstr. Modifier ici les textes propres à cette entreprise. */
window.SITE = {
  "company": "Loopstr",
  "accessCode": "chien",
  "posteCards": 4,
  "companyCards": 3,
  "mailSubject": "Candidature alternance — Timo",
  "texts": {
    "fr": {
      "nav_company": "Loopstr",
      "footer_location_value": "Montpellier / Paris",
      "landing_kicker": "Candidature · chef de projet campagnes",
      "landing_title": "Bonjour Loopstr.<span>Je suis peut-être votre homme.</span>",
      "landing_intro": "Un parcours international, une vraie culture du terrain et l’envie de faire avancer vos campagnes.",
      "access_note": "Indice : le post LinkedIn se termine par une question de la plus haute importance : team chien ou team chat ? 🐶",
      "about_p2": "Aujourd’hui, en Master Programme Grande École à Montpellier Business School, je souhaite prolonger ce fil conducteur dans une alternance en gestion de campagnes. Un métier où l’on coordonne des interlocuteurs, des contenus et des étapes pour donner vie à un projet commun.",
      "landing_pitch": "Étudiant en Master à Montpellier Business School, je cherche une alternance de deux ans (chef de projet campagnes, SDR, BDR, chargé d’affaires…) pour apprendre au contact d’une équipe et prendre progressivement des responsabilités.",
      "poste_kicker": "Pour le poste",
      "poste_title": "Ce que j’apporte <em>au poste.</em>",
      "poste_lead": "Vos critères, mes preuves : organisation, relance, cadrage, anglais et vraie curiosité pour la tech et l’IA.",
      "poste_c1_label": "01 / Organiser",
      "poste_c1_title": "Du brief à la livraison",
      "poste_c1_p": "Coordonner plusieurs interlocuteurs, tenir les délais et les validations : événements à forte affluence, dossiers en parallèle, commandes et suivi client.",
      "poste_c2_label": "02 / Relancer",
      "poste_c2_title": "Relancer et cadrer",
      "poste_c2_p": "Suivi de dossiers, relances clients et fournisseurs, négociation jusqu’à la conclusion : j’ai l’habitude de faire avancer un sujet et de tenir un cadre.",
      "poste_c3_label": "03 / Comprendre",
      "poste_c3_title": "Tech & IA au quotidien",
      "poste_c3_p": "ChatGPT Pro depuis 2022, Claude depuis 2025, WordPress, Shopify, GitHub : l’IA est un outil de travail, pas un effet de mode. Ce portfolio en est un exemple.",
      "poste_c4_label": "04 / Chiffrer",
      "poste_c4_title": "Budgets & rentabilité",
      "poste_c4_p": "Suivi budgétaire, marges, devis et reporting Excel : utile pour cadrer le budget d’une campagne et en suivre la rentabilité.",
      "co_kicker": "Pourquoi Loopstr",
      "co_title": "Ce qui m’attire chez <em>Loopstr.</em>",
      "co_lead": "Votre format me parle : apprendre en binôme, faire tourner de vraies campagnes du brief à la publication, puis prendre progressivement ma place.",
      "co_card1_title": "Des marques qui innovent.",
      "co_card1_p": "Piloter des campagnes pour de grandes marques de la tech et de l’IA, avec des créateurs ingénieurs, chercheurs ou développeurs : un terrain où il faut rester curieux et comprendre vite.",
      "co_card2_title": "Une équipe accessible.",
      "co_card2_p": "Une petite équipe qui lit chaque candidature et répond à tout le monde : j’aime ce rapport direct, où l’on apprend en voyant faire.",
      "co_card3_title": "Un apprentissage concret.",
      "co_card3_p": "Commencer en binôme, puis prendre des campagnes en main : c’est la trajectoire que je recherche.",
      "co_letter_title": "Alexandre, je serais ravi de vous montrer <em>comment je travaille.</em>",
      "co_letter_p": "Je ne vais pas vous promettre un parcours tout fait. Je peux en revanche vous proposer de la curiosité, de l’énergie et une vraie envie d’apprendre au contact de Loopstr.",
      "site_title": "Bonjour Loopstr — Timo"
    },
    "en": {
      "nav_company": "Why Loopstr",
      "footer_location_value": "Montpellier / Paris",
      "landing_kicker": "Application · Campaign Project Manager",
      "landing_title": "Hello, Loopstr.<span>I might be the person you’re looking for.</span>",
      "landing_intro": "An international background, hands-on experience and the drive to help move your campaigns forward.",
      "access_note": "Hint: the LinkedIn post ends with a question of the utmost importance: team dog or team cat? 🐶",
      "about_p2": "I am currently completing a Master in Management at Montpellier Business School. I am looking for a work-study role at the intersection of tech, influence and business.",
      "landing_pitch": "A Master’s student at Montpellier Business School, I am looking for a two-year work-study role (campaign project manager, SDR, BDR, account executive…) to learn alongside a team and gradually take on more responsibility.",
      "poste_kicker": "For the role",
      "poste_title": "What I bring <em>to the role.</em>",
      "poste_lead": "Your criteria, my evidence: organisation, follow-up, framing, English and a genuine curiosity for tech and AI.",
      "poste_c1_label": "01 / Organise",
      "poste_c1_title": "From brief to delivery",
      "poste_c1_p": "Coordinating several stakeholders, meeting deadlines and approvals: high-volume events, parallel files, orders and client follow-up.",
      "poste_c2_label": "02 / Follow up",
      "poste_c2_title": "Chasing and framing",
      "poste_c2_p": "Following files, chasing clients and suppliers, negotiating through to closing: I am used to moving a topic forward and holding a framework.",
      "poste_c3_label": "03 / Understand",
      "poste_c3_title": "Tech & AI every day",
      "poste_c3_p": "ChatGPT Pro since 2022, Claude since 2025, WordPress, Shopify, GitHub: AI is a working tool, not a trend. This portfolio is one example.",
      "poste_c4_label": "04 / Count",
      "poste_c4_title": "Budgets & profitability",
      "poste_c4_p": "Budget monitoring, margins, quotes and Excel reporting: useful for framing a campaign budget and tracking its profitability.",
      "co_kicker": "Why Loopstr",
      "co_title": "What draws me to <em>Loopstr.</em>",
      "co_lead": "Your setup appeals to me: learn alongside you, run real campaigns from brief to publication, then gradually take ownership.",
      "co_card1_title": "Brands that innovate.",
      "co_card1_p": "Running campaigns for major tech and AI brands, with creators who are engineers, researchers or developers: a field that demands curiosity and quick understanding.",
      "co_card2_title": "An approachable team.",
      "co_card2_p": "A small team that reads every application and replies to everyone: I like that direct relationship, where you learn by watching and doing.",
      "co_card3_title": "A practical way to learn.",
      "co_card3_p": "Start alongside you, then take campaigns in hand: that is the trajectory I am looking for.",
      "co_letter_title": "Alexandre, I would love to show you <em>how I work.</em>",
      "co_letter_p": "I won’t pretend to have everything figured out. I can bring curiosity, energy and a real desire to learn alongside Loopstr.",
      "site_title": "Hello Loopstr — Timo"
    }
  }
};
